## Tensor
- PyTorch把对数据的存储和操作都封装在Tensor里
- GPU计算加速
- 自动求导

### Tensor是多维数组：
- 标量（0维）：单个数，比如 torch.tensor(3.14)
- 向量（1维）：一列数，比如 torch.tensor([1,2,3])
- 矩阵（2维）：行列数据，比如 torch.tensor([[1,2],[3,4]])
- 高维张量（3维及以上）：高维数据，比如torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]])

In [ ]:
"""创建一个Tensor"""
import torch
import numpy as np
# 1D Tensor
t1 = torch.tensor([1,2,3])
print(t1)
# 2D Tensor
t2 = torch.tensor([[1,2,3],[4,5,6]])
print(t2)
# 3D Tensor
t3 = torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]])
print(t3)
print(t3.shape)  # 查看形状       torch.Size([2, 2, 2])
print(t3.dtype)  # 查看数据类型   torch.int64
print(t3.device) # 查看存储设备   cpu

# 从NumPy数组创建Tensor
arr = np.array([[1,2,3],[4,5,6]])
t_np = torch.tensor(arr)
print(t_np)



tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
torch.Size([2, 2, 2])
torch.int64
cpu
tensor([[1, 2, 3],
        [4, 5, 6]])


PyTorch里的数据类型主要为：

1. 整数型 torch.uint8、torch.int32、torch.int64。其中torch.int64为默认的整数类型。

2. 浮点型 torch.float16、torch.bfloat16、 torch.float32、torch.float64，其中torch.- float32为默认的浮点数据类型。

3. 布尔型 torch.bool

torch.float32为全精度，其他为半精度，一般情况下模型训练在全精度下进行。

混合精度训练（全精度+半精度），可以加速训练，节省显存。

In [ ]:
#自己指定数据类型
t_float = torch.tensor([1,2,3], dtype=torch.float32)
print(t_float)  # tensor([1., 2., 3.])

#布尔型torch.bool
#Bool类型在PyTorch里可以进行高效的索引操作
x = torch.tensor([1,2,3,4,5])
mask = x > 2  # 生成布尔掩码
print(mask)  # tensor([False, False,  True,  True,  True])
print(x[mask])  # 使用布尔掩码进行索引：tensor([3, 4, 5])
x[mask] = 0
print(x)  # tensor([1, 2, 0, 0, 0])

tensor([1., 2., 3.])
tensor([False, False,  True,  True,  True])
tensor([3, 4, 5])
tensor([1, 2, 0, 0, 0])


In [ ]:
# 创建tensor指定设备（默认在CPU/内存上）
#创建GPU/显存上的Tensor
t_gpu = torch.tensor([1,2,3],device = "cuda")
print(t_gpu.device)   # cuda:0

cuda:0


d:\Software\Anaconda\envs\ml_full\lib\site-packages\torch\cuda\__init__.py:235: UserWarning: 
NVIDIA GeForce RTX 5060 Laptop GPU with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5060 Laptop GPU GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(


In [ ]:
#指定值或随机值填充tensor、指定tensor形状
shape = (2,3) #设定张量的形状，即Tensor的维度
rand_tensor = torch.rand(shape) #创建元素值在[0,1)之间均匀分布的tensor
print(f"rand_tensor:{rand_tensor}")
randn_tensor = torch.randn(shape) #创建一个元素值服从标准正态分布的tensor（均值0，标准差1）
print(f"randn_tensor:{randn_tensor}")
ones_tensor = torch.ones(shape) #创建一个所有元素值都为1的tensor
print(f"ones_tensor:{ones_tensor}")
zeros_tensor = torch.zeros(shape) #创建一个所有元素值都为0的tensor
print(f"zeros_tensor:{zeros_tensor}")

#torch.full(size,value) 全value张量
twos_tensor = torch.full(shape,2) #创建一个所有元素值都为2的tensor
print(f"twos_tensor:{twos_tensor}")
eye_tensor = torch.eye(3) #创建一个3x3的单位矩阵
print(f"eye_tensor:{eye_tensor}")

rand_tensor:tensor([[0.9195, 0.8634, 0.2596],
        [0.8207, 0.0605, 0.3544]])
randn_tensor:tensor([[ 1.0194, -1.0777,  1.4600],
        [-0.0186,  0.2078,  1.8254]])
ones_tensor:tensor([[1., 1., 1.],
        [1., 1., 1.]])
zeros_tensor:tensor([[0., 0., 0.],
        [0., 0., 0.]])
twos_tensor:tensor([[2, 2, 2],
        [2, 2, 2]])
eye_tensor:tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


### Tensor的属性
__torch.randn(size, *, dtype=None, device=None, requires_grad=False)__

1. tensor形状（shape/size）

2. tensor内元素类型（dtype:默认torch.float32）

3. tensor的设备（device:CPU/GPU）

4. 计算梯度（requires_grad:是否需要计算梯度，用于深度学习）

In [ ]:
tensor = torch.rand(3,4)
print(f"Shape of tensor:{tensor.shape}") # tensor形状
print(f"Datatype of tensor:{tensor.dtype}") # tensor内元素类型
print(f"Device tensor is stored on:{tensor.device}") #tensor的设备

Shape of tensor:torch.Size([3, 4])
Datatype of tensor:torch.float32
Device tensor is stored on:cpu


### Tensor的操作
1. 形状变换 
- x = x.reshape()   按元素顺序重新组织维度
- x = x.permute()   改变元素顺序，交换tensor的维度（对于二维矩阵就是行列互换，转置）

__在PyTorch里，张量的维度（dimension/axis）是用0，1，2...表示（从0开始！！！）__

__第0个维度是行，第1个维度是列__

2. 数字运算

3. 统计函数

4. 索引、切片

5. 广播机制

#### 1、形状变换

In [ ]:

x = torch.randn(4,4) 
x_reshape = x.reshape(16)   #展平为1维向量
x_permute = x.permute(1,0)  #交换第0维和第1维，转置
print(x)
print(x_reshape)
print(x_permute)

# 对于二维tensor,可用torch.t()转置
x_t = torch.t(x)

# 扩展tensor的维度，可使用torch.unsqueeze()
x = torch.tensor([1,2,3,4])
# 扩展第0维
x_0 = x.unsqueeze(0) 
print(x_0.shape,x_0)    # torch.Size([1, 4]) tensor([[1, 2, 3, 4]])
#扩展第1维
x_1 = x.unsqueeze(1)
print(x_1.shape,x_1)    # torch.Size([4, 1]) tensor([[1],[2],[3],[4]])

# 缩减tensor的维度，可使用torch.squeeze()
# 指定需要缩减的维度索引
# 若不指定，则会把所有大小为1的维度都去掉
x = torch.ones((1,1,3)) # 3维tensor
y = x.squeeze(dim = 0) #缩减第0维
print(y.shape)  # torch.Size([1, 3])
z = x.squeeze()    #缩减所有为1的维度
print(z.shape)  # torch.Size([3]) 
 

tensor([[-1.9341,  0.4838, -0.2445, -1.1633],
        [-0.9069,  1.6950, -0.4087, -0.6391],
        [-0.9152,  1.0841, -0.1041,  0.6078],
        [ 0.2125,  0.0835, -1.6805, -0.4007]])
tensor([-1.9341,  0.4838, -0.2445, -1.1633, -0.9069,  1.6950, -0.4087, -0.6391,
        -0.9152,  1.0841, -0.1041,  0.6078,  0.2125,  0.0835, -1.6805, -0.4007])
tensor([[-1.9341, -0.9069, -0.9152,  0.2125],
        [ 0.4838,  1.6950,  1.0841,  0.0835],
        [-0.2445, -0.4087, -0.1041, -1.6805],
        [-1.1633, -0.6391,  0.6078, -0.4007]])
torch.Size([1, 4]) tensor([[1, 2, 3, 4]])
torch.Size([4, 1]) tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([1, 3])
torch.Size([3])


#### 2、数学运算

In [ ]:

a = torch.ones((2,3))
b = torch.ones((2,3))
#逐元素运算（维度不变）
print(a + b) # 加法
print(a - b) # 减法
print(a * b) # 乘法
print(a / b) # 除法
#矩阵乘法（改变维度）
print(a @ b.T)  #b.T是b的转置

#### 3、统计函数

In [ ]:

x = torch.tensor([[1,3],[1,3],[1,3]])
# 计算均值：整数tensor不能直接计算均值，需要先转换为浮点型
x = x.float()
mean_x = x.mean() # 求整个矩阵的均值 
x_sum = x.sum()   # 求和
x_std = x.std()   # 求标准差
x_var = x.var()   # 求方差
x_max = x.max()   # 求最大值
x_min = x.min()   # 求最小值

# 求均值是把指定维度消掉，其他维度保留!!!!!
x1_mean = x.mean(dim=0) # 消掉第0维，按列求均值
x2_mean = x.mean(dim=1) # 消掉第1维，按行求均值

# 统计后保持原来维度不变，不消灭统计的维度
# 指定参数 keepdim=True
x1_mean_keepdim = x.mean(dim=0,keepdim=True) # 保持第0维

#### 4、索引与切片

计数与C语言风格类似，从0开始计数，左闭右开

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(x[0,0])  # 访问第1行第1列元素，返回tensor(1)       
print(x[1])    # 访问第2行所有元素，返回一个1维tensor
print(x[:,1])  # 访问第2列所有元素，返回一个1维tensor
print(x[0:2,1:3]) # 访问第1-2行，第2-3列元素，返回一个2维tensor

tensor(1)
tensor([4, 5, 6])
tensor([2, 5, 8])
tensor([[2, 3],
        [5, 6]])


#### 5、广播机制

原则上来说，tensor的所有的逐元素运算都要求两个tensor的形状必须完全一致。

但在实际中，假如我们有一个tensor：t1。t1的shape为（3，2）。我们想给t1的每个元素都加上1。

此时我们不必构造一个shape为（3,2），元素全为1的tensor再进行相加。

我们可以直接写 t1 +1，PyTorch内部会虚拟扩展出一个形状为（3,2）的tensor，再和t1相加。

这种机制，就是广播机制。

__PyTorch 在进行广播计算时，并不会真的复制数据，而是通过调整张量的索引方式（Strided Memory Access）来实现逐元素计算。__


In [ ]:
t1 = torch.randn((3,2))
print(t1)
print(t1+1)

tensor([[ 0.3812, -1.1607],
        [ 0.3348,  1.7176],
        [-0.4116, -0.4875]])
tensor([[ 1.3812, -0.1607],
        [ 1.3348,  2.7176],
        [ 0.5884,  0.5125]])


In [ ]:
t1 = torch.ones((3,2))
print(t1)
t2 = torch.ones(2)
print(t2)
print(t1 + t2)  # 广播机制

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([1.])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


广播机制的一般原则：

1. __维度对齐__ ：如果两个tensor的维度数不同，则在较小维度的tensor的形状前面补1，直到两个tensor的维度数相同。

2. __扩展维度__ ：在 **维度值为1** 的维度上，通过虚拟复制，让两个tensor的维度值相等。

如果两个tensor在某个维度上的长度不匹配，且两个tensor在该维度上的长度都不为1，则报错。

3. __进行按位计算__ 

### 利用GPU加速计算 —— 大幅度加速

默认创建的tensor都是在CPU/内存上。让tensor转移到GPU/显存上：

1. 创建时，设定tensor的设备为“cuda”

2. 将cpu上的tensor通过to("cuda")方法转移到GPU上

检查你的环境里是否有可用的英伟达GPU: **torch.cuda.is_available()** 

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

A@B 是 torch.matmul(A,B) 的简写,可处理高维度的tensor(批量矩阵乘法)

torch.mm(A,B) 只能用于二维矩阵

### Tensor在不同设备上的计算原则
模型和张量需要显式移动到目标设备上（如 GPU）；

所有参与同一计算的张量必须位于相同设备，计算结果也会保留在该设备上。